"""Add unique constraint to Friends model

Revision ID: 1d47515036ef
Revises: 746303b3954f
Create Date: 2023-12-05 00:35:23.589345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d47515036ef'
down_revision = '746303b3954f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_friend_uc', ['user_id', 'friend_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_constraint('_user_friend_uc', type_='unique')

    # ### end Alembic commands ###
